### ISSUE TITLE
possibly outdated tutorials on how to use shuttleentrysim 

### ISSUE THREAD

**Issue by FlandreScarlet1** [giuliodondi/kOS-ShuttleEntrySim#14] opened 2024-01-13 03:22 UTC
I been struggling with using shuttleentrysim with your new shuttle model aero i even tried watching some of your videos and  and for some reason when i try to use deorbit assist it does not do anything like it doesnt show a trajectory cue on the map  when planning a deorbit burn. During reentry the script acts weird im not sure if its normal but it does not like to turn with the trajected path like i chose edwards and for some reason the shuttle rolls too much and pitches in a way i dont really think its normal im not sure too sure i shouldn't assume since you know more about the shuttle than i do but it pitches around 85 degrees during a roll and the pitch could sometimes be 40 or something but during approach the script just simply gives up with an error instead of going to approach mode which i forgot to screen shot but basically it shuts down and i have to control the shuttle manually with ksp controls and not the script since it shows error on some sort of hac error in some line 42 if i remember correctly for aerosim library but from the problem with approach when error occurs the shuttle does not auto trim so im not really sure why but its likely the error of course.  what i noticed is during reentry around 80km or 80,000 meters the shuttle really gains too much lift amd i start climbing to 100 feet a second which basically causes me to overshoot my wanted trajectory by the time i get there wanting to not be quick but atleast much less than mach 10 but speed is at mach 20. but even though im like many many kms away from the runway before i even approach sometimes since i use autosave when i think im messing up and want to try again for reentry by the time i get there to edwards i start reentry like after i pass aussie and new zealand and then start reentry over the pacific thats where i am mach 27 sometimes but when i am like 20 minutes away from approaching edwards i am still way too fast around mach 20-21 i even tried deorbitting a bit further over around africa in the east at 51.6 inclination going downwards and then i still have the same problem overshooting edwards at 51.6 going upwards and then passing edwards because of too much climb for too long instead of losing some altitude. usually i am at around 200,000 meter orbit when deorbiting to lowering to about 24,000 meters  in a path simliar to one of your video reentry script for edwards landing

**Comment by giuliodondi** [comment] 2024-01-13 09:54
You're going to have enrich this report with lots of screenshot where you walk me through exactly what you do step by step, so I can see what state you're in and have some way to tell what's going on.
Where you put your node, what you see in the deorbit planner, and how reentry progresses as you close in, in detail.

I do confirm that the videos are outdated with respect to the aero model but the basic steps are the same, and the deorbit planner is supposed to give you insight in how it's going to perform during entry. The fact that you don't see any trajectory path is already a problem and obviously things go wrong,
200km initial orbit and 24km PE altitude sounds to me far too shallow, the Shuttle has no way to generate enough drag to start slowing down. Try 300km orbit and 0km PE, and post detailed screenshots

**Comment by FlandreScarlet1** [comment] 2024-01-15 22:44
![Kerbal Space Program Screenshot 2024 01 15 - 14 43 17 65](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/8690b15e-da98-4d9b-b4af-a608c7c29a6c)
![Kerbal Space Program Screenshot 2024 01 15 - 14 43 21 65](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/b6155e4d-3de3-451f-bf73-774627decb74)
![Uploading Kerbal Space Program Screenshot 2024.01.15 - 14.43.28.18.png…]()

**Comment by FlandreScarlet1** [comment] 2024-01-15 22:45
![Kerbal Space Program Screenshot 2024 01 15 - 14 45 04 47](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/d8612963-839d-48b4-a097-2492c9e43f7f)

**Comment by FlandreScarlet1** [comment] 2024-01-16 00:41
![Kerbal Space Program Screenshot 2024 01 15 - 16 31 23 75](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/51875681-1aa6-431b-ab7a-a9e31975e99a)

**Comment by FlandreScarlet1** [comment] 2024-01-17 03:59
![Kerbal Space Program Screenshot 2024 01 16 - 19 55 06 44](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/e3392ab3-5013-46bf-8b92-343eedd7a067)
i tried doing rtls with it as well and this is what i am getting sadly it says something about hdot undefined

**Comment by FlandreScarlet1** [comment] 2024-01-17 04:04
usually for the part i did previously i usually put the node around where the around sts-128 deorbited a bit further than Australia basically its next approach during orbit and i am around 350 km ap and pe is around 800 meters close to 0km around and then i manage to get its path right even though the deorbit helping script for pathway for orbit didnt really work out no matter what i did so i gave up either way the only problem i have to taem im not sure if its on my side it probably is since im guessing no one may have any problems with it.

**Comment by FlandreScarlet1** [comment] 2024-01-17 04:05
but i did install some stuff for RSS reborn for which the files are seperated and no longer for realsolarsystem which was from ballisticfox and new volumetric 4 from blackrack so idk if those are the problem im not too sure but i hope this is enough information or if you might need more

**Comment by giuliodondi** [comment] 2024-01-18 01:15
The bug upon entering TAEM has been fixed, please pull and install the latest version fo the script.

From your screenshots I see that your parameters at entry interface are off. You are reentering too far away and too shallow, you need to move you deorbit burn closer to the site and lower your periapsis. 

Here is a quick example I did: 
![screenshot188](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/53257302/b0006cea-6e81-42a3-ba3d-1cf3545622d4)
![screenshot186](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/53257302/4d4d7ef6-b45f-49b1-af57-080e45434145)
![screenshot189](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/53257302/b9bbbc34-db6a-4f8a-93e0-9a45318598cb)
![screenshot190](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/53257302/74e619fa-6c35-4288-b2c1-025f4ec3aadb)

I'm interested in figuring out why you don't see the green reentry trajectory in the deorbit planner. If you run the deorbit planner, how quickly do the numbers update in the gui if you move around the manoeuvre node?
If the numbers do not update at all, it 's an indication that the script could be running too slowly on your machine

**Comment by FlandreScarlet1** [comment] 2024-01-20 19:43
> The bug upon entering TAEM has been fixed, please pull and install the latest version fo the script.
> 
> From your screenshots I see that your parameters at entry interface are off. You are reentering too far away and too shallow, you need to move you deorbit burn closer to the site and lower your periapsis.
> 
> Here is a quick example I did: ![screenshot188](https://private-user-images.githubusercontent.com/53257302/297566548-b0006cea-6e81-42a3-ba3d-1cf3545622d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3ODAwMTgsIm5iZiI6MTcwNTc3OTcxOCwicGF0aCI6Ii81MzI1NzMwMi8yOTc1NjY1NDgtYjAwMDZjZWEtNmU4MS00MmEzLWJhM2QtMWNmMzU0NTYyMmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE5NDE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYWQ2N2VhYmYyODM3OGY0YzZiOTM5NTU2ZDM3ZDVmMTg4Yzg0NmFiMmI4N2FjNzBiODIwZGZmOGM0YmM4YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XRXdsE5-Jnl9mkEjHo2sGc8FXjxECThqf0Ljx5_h2mk) ![screenshot186](https://private-user-images.githubusercontent.com/53257302/297566524-4d4d7ef6-b45f-49b1-af57-080e45434145.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3ODAwMTgsIm5iZiI6MTcwNTc3OTcxOCwicGF0aCI6Ii81MzI1NzMwMi8yOTc1NjY1MjQtNGQ0ZDdlZjYtYjQ1Zi00OWIxLWFmNTctMDgwZTQ1NDM0MTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE5NDE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNjlhNDIyZTkwYTY5NTkyOWUwZjQ2OTdhMDBiZjczM2UwM2JiOWFiMmI0OGU2OTU4YjFmODA1MjU1Y2VmMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZQk4slHzWpq4z3gNgen_X2BQlUPtO6AR3xn-1GIjsRY) ![screenshot189](https://private-user-images.githubusercontent.com/53257302/297566595-b9bbbc34-db6a-4f8a-93e0-9a45318598cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3ODAwMTgsIm5iZiI6MTcwNTc3OTcxOCwicGF0aCI6Ii81MzI1NzMwMi8yOTc1NjY1OTUtYjliYmJjMzQtZGI2YS00ZjhhLTkzZTAtOWE0NTMxODU5OGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE5NDE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MTUxOGY4NDA4NzEzOGY3MmRjMzVhYzJjYWIxYWExNGE5OThhMDI3MzA5ZjM3NTY3ZjViMGVkMDY5MGY3YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KjsOWYNYOdVLBM1fSMPG5_T6ZjyMKAu34U9-N1H64Kg) ![screenshot190](https://private-user-images.githubusercontent.com/53257302/297566603-74e619fa-6c35-4288-b2c1-025f4ec3aadb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3ODAwMTgsIm5iZiI6MTcwNTc3OTcxOCwicGF0aCI6Ii81MzI1NzMwMi8yOTc1NjY2MDMtNzRlNjE5ZmEtNmMzNS00Mjg4LWIyYzEtMDI1ZjRlYzNhYWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE5NDE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYTFhNDU3ZDU2ZWI2OTMzMWY0ZWRmOGY0YWFhYmM2YmNhZDU5NDQ3NjBjMWQ2MWRkZmYwYWU1YjVlN2MwMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9XP7AfGXwiY9nW7SPA3j_YuY4JuPFms-KqgSzgoNJNw)
> 
> I'm interested in figuring out why you don't see the green reentry trajectory in the deorbit planner. If you run the deorbit planner, how quickly do the numbers update in the gui if you move around the manoeuvre node? If the numbers do not update at all, it 's an indication that the script could be running too slowly on your machine

yea the thing does not update when i like move the time to burn the green line also moves further back
![Kerbal Space Program Screenshot 2024 01 20 - 10 43 48 79](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/a01fa402-805d-412c-a8cd-7b457b2e0d35)

**Comment by FlandreScarlet1** [comment] 2024-01-20 19:45
is it possibly kos setting or maybe trajectory mod maybe causing it? like do i have to have some certain setting on for trajectory or kos?

**Comment by FlandreScarlet1** [comment] 2024-01-21 03:18
or is there a way to fix trajectory by any chance?

**Comment by FlandreScarlet1** [comment] 2024-01-21 03:21
i did get some logs for entry sim 

[entry_log.csv](https://github.com/giuliodondi/kOS-ShuttleEntrySim/files/13999881/entry_log.csv)
[entry_log_old.csv](https://github.com/giuliodondi/kOS-ShuttleEntrySim/files/13999882/entry_log_old.csv)

**Comment by FlandreScarlet1** [comment] 2024-01-21 03:21
but they say nothing so idk but is there a problem with trajectory like i know there probably wont be nothing to fix at your end but like im having trouble on my end like these are all the mods i have for example if any interfere which im not sure 
![Desktop Screenshot 2024 01 20 - 21 04 37 36](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/f8360b78-8f0c-4ea2-bac8-f25ec2e1846b)

**Comment by FlandreScarlet1** [comment] 2024-01-22 04:01
how do you get trajectory line to extend and not be behind like the trajectory red line i tried everything since everything i tried getting rid of rss reborn nothing i tried older versions of trajectories and even removed some mods of kos and nothing i really tried. why i dont know why its happening to me.

**Comment by FlandreScarlet1** [comment] 2024-01-22 04:02
do i need like remotetech mod?

**Comment by giuliodondi** [comment] 2024-01-22 09:20
you don't need RemoteTech or any other mod, they're not listed as requirements.
You also don't need Trajectories if you already have Principia, if it's a source of confusion for you get rid of it.

In your screenshots I never saw you use the Principia surface-relative trajectory mode, so I can't tell if you're placing the deorbit burn on the correct orbital pass. Maybe you're just too far away. 
Try removing Trajectories, setting Principia to surface-relative and then planning your deorbit burn. Send a screenshot.

A note on performance:
These scripts are heavy to run, that's why the IPU setting is set way high inside them. Your KSP is full of mods, running them and the script on top requires a beefy PC.
Have you considered that maybe your machine is not up to the task, and tried removing some mods?
And by the way: reducing the IPU setting will lighten the load on KSP but result in a script that doesn't run fast enough, so thta's not a solution.

**Comment by FlandreScarlet1** [comment] 2024-01-22 13:41
> you don't need RemoteTech or any other mod, they're not listed as requirements. You also don't need Trajectories if you already have Principia, if it's a source of confusion for you get rid of it.
> 
> In your screenshots I never saw you use the Principia surface-relative trajectory mode, so I can't tell if you're placing the deorbit burn on the correct orbital pass. Maybe you're just too far away. Try removing Trajectories, setting Principia to surface-relative and then planning your deorbit burn. Send a screenshot.
> 
> A note on performance: These scripts are heavy to run, that's why the IPU setting is set way high inside them. Your KSP is full of mods, running them and the script on top requires a beefy PC. Have you considered that maybe your machine is not up to the task, and tried removing some mods? And by the way: reducing the IPU setting will lighten the load on KSP but result in a script that doesn't run fast enough, so thta's not a solution.

I have an rtx 4070 ti and i5 14600kf im guessing those are not enough with the ksp mods i have

**Comment by FlandreScarlet1** [comment] 2024-01-23 03:09
nvm i got it working

**Comment by FlandreScarlet1** [comment] 2024-01-23 03:38
it was because i had realsolarsystem installed with new blackracks rss configs i think that was probably the issue

**Comment by giuliodondi** [comment] 2024-01-23 08:29
good, do you mind sending a couple screenshots just so I can confirm everything is ok and close the ticket?

**Comment by FlandreScarlet1** [comment] 2024-01-23 21:26
![Kerbal Space Program Screenshot 2024 01 23 - 13 26 23 58](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/636e98ae-34a7-4a02-808b-19f29c13c24a)
![Kerbal Space Program Screenshot 2024 01 23 - 13 26 14 18](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/516b05b5-2c58-44cc-98d3-86bcf9e222ba)

**Comment by FlandreScarlet1** [comment] 2024-01-24 04:46
also one more thing just letting you know if you didnt maybe catch this yet but: this may have something to do with the shuttle entry sim since it is used for landing: but for rss reborn i noticed that once i reach my destination the edwards and vandenberg map is kinda weird and also for cape just letting you know in case
![Kerbal Space Program Screenshot 2024 01 23 - 20 45 24 81](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/330cb687-ada1-4f5d-ae63-b9cc88b1b0b0)
![Kerbal Space Program Screenshot 2024 01 23 - 20 45 20 43](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/9607a115-2615-4d16-9981-dd71b569a3c6)
@
![Kerbal Space Program Screenshot 2024 01 23 - 20 46 36 65](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/0c376843-9fbf-4fdb-a65a-c914b11aeb4b)

**Comment by FlandreScarlet1** [comment] 2024-01-24 04:48
but thats all it works the shuttle entry sim btw sorry i gave you a hard time its because sometimes ksp mods can be frustrating and also im sort of new to github btw if i dont mind asking for next time where i can make an issue because in some of the other things you made i couldnt make them only on this one since theres an issue option but im not sure how to on the others if you could show me as well.

**Comment by giuliodondi** [comment] 2024-01-24 08:29
> ![Kerbal Space Program Screenshot 2024 01 23 - 13 26 14 18](https://private-user-images.githubusercontent.com/142283370/299107245-516b05b5-2c58-44cc-98d3-86bcf9e222ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODQ3ODUsIm5iZiI6MTcwNjA4NDQ4NSwicGF0aCI6Ii8xNDIyODMzNzAvMjk5MTA3MjQ1LTUxNmIwNWI1LTJjNTgtNDRjYy05OGQzLTg2YmNmOWUyMjJiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQwODIxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWUyYTNhZTZhMWUxZjI2NWUxM2Y3ZTJkNjM2NzIzMTgxOGM4ZDA0YmRkODJmN2Y0NWRjMmVkZThkYjAwZDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pICl1Pc_bdlBOBxG3rwW6reGTXqulk-gUyEjaq3P-gU)

In this image I can see the script working as expected. However, you need to adjust how you use it.
Use the Principia surface-relative trajectory mode to see which orbital pass comes closest to your site, you toggle it by switching to surface-velocity like in stock KSP. Also you're too far away, you range at entry interface should be around 7000 km. You need to see roll reversals in your trajectory, which you don't in your case.  
Again, the videos are not super up-to-date but they show you the gist

> also one more thing just letting you know if you didnt maybe catch this yet but: this may have something to do with the shuttle entry sim since it is used for landing: but for rss reborn i noticed that once i reach my destination the edwards and vandenberg map is kinda weird and also for cape just letting you know in case 

The KK statics are of course related to landing, yes, but they're not related to the entry script directly, all the script needs to know is contained in the landing sites .ks file.
Also, this is obviously a consequence of the fact that we're using two different RSS height map. Nothing I can do to prevent this. That's why the entry script comes with a helper script to measure runway data and I teach you how to use it in the README.

Finally, I've made sure that it's possible to open issues on all my repositories.
The Shuttle System fork did not have issues enabled by default because it was a fork of SpaceODY's repository, that's an error on my part, but it's now fixed.
For the future: Issue reports are meant to be germane to the repository and **focus on one specific problem**.  
When you start throwing in three separate problems at once it becomes impossible to figure out what causes what and what fixes what. I'll always be willing to take time to help others using my stuff, but let's meet somewhere halfway

**Closed as completed by giuliodondi** 2024-01-24 08:29 UTC
