### ISSUE TITLE
airbrake_control issue

### ISSUE THREAD

**Issue by Serpatron** [giuliodondi/kOS-ShuttleEntrySim#9] opened 2023-10-30 20:45 UTC
![image](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/46377922/8b3969dc-53e0-438c-b70c-45f09249f750)
Hi! I've been running into this issue attempting to use the new splitbrake/body flap function. I made a clean install of the mods/scripts to ensure everything was updated properly but still received the error. Wondering if you happened to know anything about this. 

Thanks!

**Comment by giuliodondi** [comment] 2023-10-31 09:19
This error means that the script cannot find the stock control surface modules that it needs to actuate the speedbrake.
I'm assuming you did indeed install the latest of not just the reentry script stuff but also my fork of Space-Shuttle-System. In this situation, this error should not be possible.

Unfortunately there's a quirk in the KSP craft file system: some part modules get saved along with the part itself in the craft part tree. This means that even if the part is modified, the actual instance of that part for that particular craft might not inherit the modifications.

So please do the following:
- verify that the Shuttle-system mod is up to date with my fork
- re-assemble the Orbiter from scratch in the VAB/SPH
- right-click the rudder, expand all control surface fields, and post a screenshot

**Comment by Serpatron** [comment] 2023-11-01 01:41
Makes sense. Thank you for your reply. I figured that was what that error meant, hence my immense confusion. I reinstalled everything, ensured that I am using the most up-to-date versions of both your scripts and your fork of Shuttle-system, and rebuilt the craft from scratch (even using a new save for good measure).
![image](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/46377922/bbdc8515-5e41-4e9e-9c6b-be12b58f02e7)

**Comment by giuliodondi** [comment] 2023-11-06 09:02
That's puzzling, the part modules look fine and in principle there's no reason why the script should break.

In any case, I made some changes to the flap/airbrake control scheme and tested them. Try updating the entry script once again, deleting all the source files.

**Comment by FlandreScarlet1** [comment] 2023-11-10 19:15
![Kerbal Space Program Screenshot 2023 11 10 - 11 14 33 70](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/9625ac10-ede9-4289-8191-932eca7b283c)
problem is still there

**Comment by giuliodondi** [comment] 2023-11-10 19:29
You didn't show me your control modules in the tail control surface part, they might be out of date.

This is how it's supposed to look:
![screenshot142](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/53257302/e885e1a0-56cd-461a-b65e-f80d67a2356c)

and with speedbrakes open:
![screenshot143](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/53257302/4388e754-cba5-4d1e-8882-7944c1537e22)

**Comment by FlandreScarlet1** [comment] 2023-11-11 03:34
![Kerbal Space Program Screenshot 2023 11 10 - 19 34 16 65](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/d2d7be7d-b614-4270-9b68-59c0142659a0)

**Comment by Serpatron** [comment] 2023-11-11 03:35
Can confirm issue still persists for me as well after installing everything over again with your updates. Made sure to remove all previous files as well. Let me know if there's anything else you'd like me to try. Thank you for your help in trying to diagnose this!

**Comment by giuliodondi** [comment] 2023-11-11 14:26
I just did a quick test for you:

- Brand new empty KSP install (1.12.5 although 1.12.3 should be fine)
- Installed the following mods via CKAN:
    - RSS
    - Realism Overhaul + all dependencies and recommended mods (in particular Textures Unlimited and Waterfall)
    - kOS
    - ASET Consolidated Avionics Pack
    - B9 Parts Switch (the 1.12.3 version)
    - KSPWheel
 - installed the following mods manually in this order:
     - [my fork of Ferram](https://github.com/giuliodondi/Ferram-Aerospace-Research-modded), pasting just the GameData folder
     - my Shuttle System fork
     - the entry script (don't forget the GameData/kOS-Addons)

Fired up KSP, new install, quickly assembled the Space Shuttle from scratch and ran the script, works exactly as intended:
![screenshot0](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/53257302/b62bd211-ec93-47a8-be7a-85020a23cb60)

**Comment by FlandreScarlet1** [comment] 2023-11-11 17:35
did you use your Realism Overhaul download or the ckan one?

**Comment by giuliodondi** [comment] 2023-11-11 18:45
ckan

**Comment by FlandreScarlet1** [comment] 2023-11-12 07:16
welp i guess i have to uninstall all my mods?

**Comment by giuliodondi** [comment] 2023-11-12 12:41
I just wanted to show that putting all the right files in the right place leads to a working script without the probl3m you brought up. 
As far as this issue report is concerned, if I can't reproduce the same problem then there is nothing to fix in this script.

**Comment by FlandreScarlet1** [comment] 2023-11-12 20:35
alright also what mod did you use to get waterfall booster thing?

**Comment by FlandreScarlet1** [comment] 2023-11-12 20:35
srb

**Comment by giuliodondi** [comment] 2023-11-12 21:41
> alright also what mod did you use to get waterfall booster thing?

This question is unrelated to the original issue, it's not even about the same repository

**Comment by Serpatron** [comment] 2023-11-12 21:46
> I just wanted to show that putting all the right files in the right place leads to a working script without the probl3m you brought up. As far as this issue report is concerned, if I can't reproduce the same problem then there is nothing to fix in this script.

Yeah, obviously if it's not reproducible on your end there's not much we can do about it. I'll try to do a fresh RO install and see if that works, but I'm good to close this thread if that suits you. Thank you for taking the time to look into it for me.

**Comment by FlandreScarlet1** [comment] 2023-11-13 02:42
is there any solution index out of range shuttle tail i redownloaded it and still

**Comment by FlandreScarlet1** [comment] 2023-11-13 02:42
like could it possibly be kos or something? conflicting it?

**Comment by giuliodondi** [comment] 2023-11-13 09:59
Please do the following so I can investigate further:

- spawn the Shuttle on the runway, open the kOS terminal, execute the following command: 
**print ship:parts.**  
and post a screenshot with the output.
- execute 
**clearscreen.**
- execute the following command: 
**print ship:partsdubbed("ShuttleTailControl")[0]:modules.** 
 and post a second screenshot with the output.

also write down your version of RO and kOS, although I don't think there's a compatibility issue

**Comment by FlandreScarlet1** [comment] 2023-11-13 23:26
![Kerbal Space Program Screenshot 2023 11 13 - 15 20 47 10](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/d00edf27-34e6-4fb2-98e4-9b3301720cb6)
![Kerbal Space Program Screenshot 2023 11 13 - 15 22 52 96](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/1b45daab-18e8-4587-82fc-0dcf43e27e3d)
RO version latest on ckan 17.6.0.1 KOS version latest on ckan 1:1.4.0.0

**Comment by giuliodondi** [comment] 2023-11-14 00:22
The second screenshot has the output truncated by the terminal, evident by the fact that items [0] and [1] of the list are nowhere to be found. 
Please re-do that command, taking care to make the terminal bigger and make sure the window is clear before doing it. Make sure no entries are truncated off-screen before taking the screenshot.


An on second thoughts: your install is full of mods.
Did you follow the steps I laid out, to try to install the Shuttle mods on a vanilla KSP?

**Comment by FlandreScarlet1** [comment] 2023-11-14 00:49
I use ksp on steam 
![Kerbal Space Program Screenshot 2023 11 13 - 16 48 57 60](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/168a6d56-244f-49ca-bb39-af38232963f2)

**Comment by giuliodondi** [comment] 2023-11-14 00:57
> I use ksp on steam 

I'm not sure what this is supposed to mean. If you're trying to tell me that it's impossible to have two separate installs if you play KSP on steam, I assure you it is not, you just have to find the right tutorials.

In any case, you last screenshot finally gave me some good info. The first "ModuleControlSurface" has an unexpected name, some googling revealed the culprit is Atmospheric Autopilot, which apparently renames those modules.
Remember when I asked to try an install only with the mods I listed? 

For the moment, this means that the script is incompatible with Atmospheric Autopilot, so you should remove it. In the future, I'll see if it's possible to make thw two work together

**Comment by FlandreScarlet1** [comment] 2023-11-14 01:02
thank you

**Comment by giuliodondi** [comment] 2023-11-14 01:12
Let me know if this works for both of you and then we can close the issue

**Comment by FlandreScarlet1** [comment] 2023-11-14 01:28
alright

**Comment by FlandreScarlet1** [comment] 2023-11-14 01:35
![Kerbal Space Program Screenshot 2023 11 13 - 17 35 35 74](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/d4c28164-5373-4934-993a-78e116d4267b)

**Comment by FlandreScarlet1** [comment] 2023-11-14 01:37
![Kerbal Space Program Screenshot 2023 11 13 - 17 37 31 35](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/f7ffd88e-e005-47a5-afa5-67d146240979)

**Comment by FlandreScarlet1** [comment] 2023-11-14 02:35
nvm it works
![Kerbal Space Program Screenshot 2023 11 13 - 18 35 26 43](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/142283370/dc864418-42b0-449b-b4d8-1096e4061a2f)

**Comment by Serpatron** [comment] 2023-11-14 03:14
> Let me know if this works for both of you and then we can close the issue

Heh, how about that. Worked a trick. At first I was surprised that AA was the issue but with hindsight it makes total sense. Your help has been much appreciated and I'm looking forward to seeing your future work on this!

**Closed as completed** 2023-11-15 13:24 UTC
